name: run MyCrawlForLib

on:
  workflow_dispatch:
  schedule:
    - cron: '10 13 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step1_Set up Python Env
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Step2_Install dependencies
        run: python -m pip install requests bs4
      - name: Step3_Run Crawl
        run: python app01.py
