name: run MyCrawlForLib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step1______Set up Python Env
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Step2______Install dependencies
        run: python -m pip install requests bs4
      - name: Step3______Run Crawl
        run: python app01.py
